material-components/material-design-for-wordpress

.github/PULL_REQUEST_TEMPLATE.md, bin/tag-built.sh, composer.json, contributing/engineering.md, contributing/project-management.md, package.json, plugin/material-design.php, plugin/readme.md, plugin/readme.txt, readme.md
=> Update repo references to new Github repo url

plugin/assets/src/block-editor/blocks/card/components/card-image-edit.js, plugin/assets/src/block-editor/blocks/card/components/card-image.js, plugin/assets/src/block-editor/blocks/card/components/horizontal-card-layout.js, plugin/assets/src/block-editor/blocks/card/components/vertical-card-layout.js, plugin/assets/src/block-editor/blocks/card/editor.css, plugin/tests/js/block-editor/blocks/card/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/__snapshots__/card-image-edit.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/__snapshots__/card-image.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/card-image-edit.test.js, plugin/tests/js/block-editor/blocks/cards-collection/__snapshots__/edit.test.js.snap
=> Can't remove image from card

Gruntfile.js, plugin/assets/src/block-editor/blocks/image-list/block.json, plugin/assets/src/block-editor/components/layout-controls/index.js, plugin/assets/src/block-editor/constants.js, plugin/readme.md, theme/README.md, theme/style.css
=> Update gallery default columns for desktop and add tooltips

plugin/assets/src/block-editor/blocks/card/editor.css, plugin/assets/src/block-editor/components/posts-control/item.js, plugin/php/rest/class-design-assets-rest-controller.php
=> Add WP_Error namespace and no title default title

plugin/assets/src/block-editor/blocks/card/block.json, plugin/assets/src/block-editor/blocks/card/components/card-image.js, plugin/assets/src/block-editor/blocks/card/components/horizontal-card-layout.js, plugin/assets/src/block-editor/blocks/card/components/vertical-card-layout.js, plugin/assets/src/block-editor/blocks/card/deprecated.js, plugin/assets/src/block-editor/blocks/card/edit.js, plugin/assets/src/block-editor/blocks/card/editor.css, plugin/assets/src/block-editor/blocks/card/index.js, plugin/assets/src/block-editor/blocks/card/save.js, plugin/assets/src/block-editor/blocks/cards-collection/block.json, plugin/assets/src/block-editor/blocks/cards-collection/deprecated.js, plugin/assets/src/block-editor/blocks/cards-collection/index.js, plugin/assets/src/block-editor/blocks/cards-collection/save.js, plugin/tests/js/block-editor/blocks/card/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/card/card.test.js, plugin/tests/js/block-editor/blocks/cards-collection/cards-collection.test.js
=> Fix card image remove

plugin/assets/css/src/block-editor.css, plugin/assets/css/src/components/material.css, plugin/assets/src/block-editor/components/icon-picker/index.js, plugin/assets/src/block-editor/components/layout-controls/index.js, plugin/assets/src/settings/utils/promises.js
=> Fix/settings WordPress 5.2

.github/PULL_REQUEST_TEMPLATE.md
=> Fix PR template links

.github/workflows/lint-tests.yml
=> Add docker layer caching to speed up build process

plugin/php/block-patterns/button.php, plugin/php/class-block-patterns.php, plugin/php/class-plugin.php, plugin/tests/phpunit/php/class-test-block-patterns.php, plugin/tests/phpunit/php/class-test-plugin.php
=> Block patterns setup

Gruntfile.js
=> Update wp-assets path for grunt wp_deploy

plugin/assets/css/src/components/material.css, plugin/assets/src/block-editor/blocks/button/block.json, plugin/assets/src/block-editor/blocks/button/edit.js, plugin/assets/src/block-editor/blocks/button/options.js, plugin/assets/src/block-editor/blocks/button/save.js, plugin/tests/js/block-editor/blocks/button/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/button/__snapshots__/save.test.js.snap, plugin/tests/js/block-editor/blocks/button/edit.test.js, plugin/tests/js/block-editor/blocks/button/save.test.js
=> Large button

plugin/php/block-patterns/hero-section-image.php, plugin/php/class-block-patterns.php, plugin/tests/phpunit/php/class-test-block-patterns.php
Fixes #37 
Editor preview: 
Mobile:
Desktop:
=> Hero section + Image Pattern

plugin/php/block-patterns/latest-posts.php, plugin/php/class-block-patterns.php, plugin/tests/phpunit/php/class-test-block-patterns.php, theme/assets/css/src/components/entry-content.css
Fixes #95 
Preview:
Mobile:
Desktop:
=> Latest posts pattern

plugin/assets/src/getting-started/reducer.js, plugin/assets/src/wizard/components/notice/index.js, plugin/assets/src/wizard/utils.js, plugin/material-design.php, plugin/php/class-admin.php, plugin/php/rest/class-design-assets-rest-controller.php, plugin/php/updates/class-update-fonts.php, plugin/readme.md, plugin/readme.txt, plugin/tests/js/wizard/components/notice/__snapshots__/index.test.js.snap
Fixes #158
I don't why the plugin/php/block-patterns/button.php file is in here
This also fixed a bad error message if the Font API key is not set
=> Bug/#158 route bug on wp.org

theme/README.md, theme/readme.txt, theme/style.css
=> Bump theme to 0.3.1

bin/local-dev/wordpress/Dockerfile, package-lock.json, package.json, plugin/assets/src/wizard/components/notice/index.js
- Add `sanitize-html` npm package.
- Sanitize error message.
=> Sanitize error message

bin/local-dev/wordpress/Dockerfile, package-lock.json, package.json, plugin/assets/src/getting-started/reducer.js, plugin/assets/src/wizard/components/notice/index.js, plugin/assets/src/wizard/utils.js, plugin/material-design.php, plugin/php/class-admin.php, plugin/php/class-importer.php, plugin/php/rest/class-design-assets-rest-controller.php, plugin/php/updates/class-update-fonts.php, plugin/readme.md, plugin/readme.txt, plugin/tests/js/wizard/components/notice/__snapshots__/index.test.js.snap, theme/README.md, theme/readme.txt, theme/style.css
Fix onboarding wizard. (See #160)
Thanks to the many contributors who made this release possible through work on development, design, testing, project management, and more:
> @rodydavis, @pbearne, @PatelUtkarsh, @emeaguiar, @csossi, @jauyong, @mattchungxwp
=> Release 0.3.1

.gitignore, theme/assets/css/src/base/masonry-grid.css, theme/assets/src/customizer/customize-preview.js, theme/assets/src/front-end/components/masonry.js, theme/assets/src/front-end/index.js, theme/inc/customizer.php, theme/template-parts/archive-card.php, theme/template-parts/content.php
Fixes #15 
This introduces a new JS masonry component that calculates sizes, updates sort order to be:
1 - 2 - 3
4 - 5 - 6
Instead of the current:
1 - 3 - 5
2 - 4 - 6
Demo:
https://share.getcloudapp.com/jkuPWX9A
=> Masonry Layout

.github/workflows/lint-tests.yml, plugin/php/class-block-types.php, plugin/tests/phpunit/php/class-test-block-types.php
=> Use WP 5.6 and up for GH action

composer.json, composer.lock, package-lock.json, package.json, plugin/assets/src/block-editor/blocks/list/components/list-item-compat.js, plugin/assets/src/block-editor/blocks/list/components/list-item.js, plugin/assets/src/block-editor/blocks/list/edit.js, plugin/php/class-block-types.php, plugin/tests/bootstrap.php
=> Replace RichText with block-editor rich text

plugin/assets/src/customizer/components/color-control/index.js, theme/assets/src/customizer/customize-controls.js, theme/assets/src/customizer/customize-preview.js
=> Fix inconsistencies with background color

plugin/assets/css/src/components/material.css, plugin/assets/src/customizer/components/color-control/index.js, plugin/assets/src/customizer/components/style-settings-control/index.js, plugin/assets/src/customizer/customize-controls.js, plugin/tests/e2e/config/bootstrap.js
=> Update linked option when parent changes

.github/workflows/lint-tests.yml, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt, theme/style.css
=> Bump support version to 5.8.1

plugin/assets/src/block-editor/blocks/list/components/list-item.js, plugin/assets/src/block-editor/blocks/list/edit.js, plugin/tests/e2e/specs/block-editor/blocks/list/list.spec.js
=> Material List Block: Fix state on change event

theme/block-template-parts/footer.html, theme/block-template-parts/header.html, theme/block-template-parts/post-meta.html, theme/block-templates/index.html, theme/block-templates/page.html, theme/block-templates/search.html, theme/block-templates/single.html, theme/inc/customizer.php, theme/theme.json
=> Add theme.json, block-templates and block-template-parts

.github/workflows/lint-tests.yml, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt
=> Bump tested upto 5.8.2

plugin/assets/src/block-editor/blocks/buttons/components/block-icon.js, plugin/assets/src/block-editor/blocks/hand-picked-posts/components/posts-picker.js, plugin/assets/src/block-editor/blocks/hand-picked-posts/index.js, plugin/assets/src/block-editor/blocks/image-list/edit.js
=> Add useCallback dependency

plugin/material-design.php, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt, theme/style.css
=> Bump to 0.5.1

theme/footer.php
=> Fix footer inconsistency 🐛 

theme/inc/customizer/colors.php
=> Update reference from wp-core

.gitignore, theme/assets/css/src/components/top-app-bar.css, theme/assets/src/block-editor/blocks/dark-mode-switch/block.json, theme/assets/src/block-editor/blocks/dark-mode-switch/button.js, theme/assets/src/block-editor/blocks/dark-mode-switch/edit.js, theme/assets/src/block-editor/blocks/dark-mode-switch/index.js, theme/assets/src/block-editor/blocks/dark-mode-switch/save.js, theme/block-template-parts/header.html
=> [FSE] Dark Switch block

.wp-env.json, contributing/engineering.md
=> Add support and guide for wp-env

composer.json
=> Add composer allowed plugin to execute

plugin/assets/src/block-editor/blocks/card/block.json, plugin/assets/src/block-editor/blocks/card/index.js, plugin/tests/js/block-editor/blocks/card/card.test.js, theme/block-templates/404.html
=> Add 404 template

theme/assets/src/block-editor/blocks/back-to-top/block.json, theme/assets/src/block-editor/blocks/dark-mode-switch/block.json, theme/assets/src/block-editor/blocks/search/block.json
=> Add block text-domain in block.json

theme/assets/src/block-editor/blocks/query-pagination-first/edit.js, theme/assets/src/block-editor/blocks/query-pagination-first/index.js, theme/assets/src/block-editor/blocks/query-pagination-last/edit.js, theme/assets/src/block-editor/blocks/query-pagination-last/index.js, theme/assets/src/block-editor/blocks/query-pagination-next/edit.js, theme/assets/src/block-editor/blocks/query-pagination-next/index.js, theme/assets/src/block-editor/blocks/query-pagination-previous/edit.js, theme/assets/src/block-editor/blocks/query-pagination-previous/index.js, theme/assets/src/block-editor/blocks/query-pagination/block.json, theme/assets/src/block-editor/blocks/query-pagination/edit.js, theme/assets/src/block-editor/blocks/query-pagination/hooks.js, theme/assets/src/block-editor/blocks/query-pagination/index.js, theme/template-parts/blocks/query-pagination-first.php, theme/template-parts/blocks/query-pagination-last.php, theme/template-parts/blocks/query-pagination-next.php, theme/template-parts/blocks/query-pagination-previous.php, theme/template-parts/blocks/query-pagination.php
=> Material Pagination Patch

theme/assets/css/src/components/footer.css, theme/assets/src/customizer/customize-preview.js, theme/inc/customizer/colors.php
https://user-images.githubusercontent.com/5015489/148556569-7f419ddf-bce0-4142-a024-8baddc224eb9.mp4
Fixes #278
=> Fix footer color and preview

theme/block-template-parts/footer.html, theme/theme.json
=> Allow padding and margin; Fix footer margin

theme/assets/src/block-editor/hooks.js, theme/inc/blocks/class-blocks.php
=> Use Additional classes metabox instead of PHP replacement

theme/inc/block-editor.php, theme/inc/customizer/header-footer.php
=> Hide footer customizer control for fse

theme/assets/css/src/editor.css
=> Import logo style in editor

theme/assets/src/block-editor/blocks/search-header-title/edit.js
=> Use rich text for editing search result placeholder

package-lock.json, package.json, phpcs-theme.xml, plugin/assets/src/block-editor/index.js, plugin/assets/src/block-editor/plugins/elevationStyle/index.js, plugin/assets/src/block-editor/plugins/index.js, plugin/php/class-block-types.php, theme/assets/src/block-editor/blocks/card/block.json, theme/assets/src/block-editor/blocks/card/elevationControl.js, theme/assets/src/block-editor/blocks/card/inspectControl.js, theme/template-parts/blocks/card-query.php
Fixes #237 
https://user-images.githubusercontent.com/5015489/152793556-98926efe-848e-4dd7-b72b-e6a6feb11efe.mp4
=> FSE: Material query card - Add elevation style

theme/assets/css/src/components/logo.css, theme/assets/css/src/components/top-app-bar.css, theme/assets/css/src/editor.css
=> Import material component for editor

.github/workflows/build-and-deploy.yml, bin/deploy-to-staging.sh
- Maps full site editing auto deploy to `full-site-editing` branch.
- Maps develop with `master` branch.
Fixes #275
=> Add staging auto deploy script

theme/functions.php, theme/inc/blocks/block-patterns.php, theme/inc/blocks/patterns/material-card-image.php, theme/inc/blocks/patterns/material-card.php
Fixes #
https://user-images.githubusercontent.com/5015489/157681035-db7d86c5-7b7d-49bb-94e1-120f2feeb650.mp4
=> Add query pattern with card and image card

theme/assets/src/front-end/components/masonry.js
=> Fix image card for masonry

theme/assets/css/src/components/tab-bar.css, theme/assets/src/block-editor/blocks/back-to-top/block.json, theme/assets/src/block-editor/blocks/card-image/block.json, theme/assets/src/block-editor/blocks/card/block.json, theme/assets/src/block-editor/blocks/dark-mode-switch/block.json, theme/assets/src/block-editor/blocks/drawer-close/block.json, theme/assets/src/block-editor/blocks/drawer/block.json, theme/assets/src/block-editor/blocks/hamburger-menu/block.json, theme/assets/src/block-editor/blocks/hamburger-menu/edit.js, theme/assets/src/block-editor/blocks/header-search-bar/block.json, theme/assets/src/block-editor/blocks/navigation-link/block.json, theme/assets/src/block-editor/blocks/navigation/block.json, theme/assets/src/block-editor/blocks/query-pagination-first/block.json, theme/assets/src/block-editor/blocks/query-pagination-last/block.json, theme/assets/src/block-editor/blocks/query-pagination-next/block.json, theme/assets/src/block-editor/blocks/query-pagination-previous/block.json, theme/assets/src/block-editor/blocks/query-pagination/block.json, theme/assets/src/block-editor/blocks/search-header-title/block.json, theme/assets/src/block-editor/blocks/search/block.json, theme/inc/block-editor.php
=> Fix header style; Fix active hamburger state

theme/assets/src/front-end/components/search.js, theme/template-parts/blocks/navigation-link.php
=> Move search bar to appropriate location for expand

theme/template-parts/blocks/card-query.php, theme/template-parts/blocks/image-card-query.php
=> Rename global vars

.github/workflows/build-and-deploy.yml
=> Add checkout step to run script

plugin/assets/src/customizer/components/google-fonts-control/item.js, plugin/assets/src/customizer/components/google-fonts-control/style.css, plugin/tests/js/customizer/components/google-fonts-control/__snapshots__/item.test.js.snap
=> Add spacing; Move font size as first

plugin/assets/src/customizer/components/google-fonts-control/item.js, plugin/assets/src/customizer/components/google-fonts-control/style.css, plugin/tests/js/customizer/components/google-fonts-control/__snapshots__/item.test.js.snap
Reverts material-components/material-design-for-wordpress#359
=> Revert "Add spacing; Move font size as first"

plugin/assets/src/block-editor/blocks/button/block.json, plugin/assets/src/block-editor/blocks/buttons/edit.js, plugin/assets/src/block-editor/blocks/buttons/save.js, plugin/assets/src/block-editor/blocks/image-list/edit.js, plugin/tests/js/block-editor/blocks/buttons/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/image-list/__snapshots__/edit.test.js.snap, plugin/tests/phpunit/php/class-test-block-types.php
=> Fix button and image list block invalidation issue

plugin/material-design.php, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt, theme/style.css
=> Bump to 0.6.0

plugin/assets/css/src/block-editor.css, theme/assets/css/src/base/typography.css, theme/inc/block-editor.php, theme/theme.json
=> Allow picking typography token in Gutenberg

plugin/assets/src/customizer/customize-preview.js
=> Fix FSE color preview

plugin/assets/src/customizer/components/color-control/style.css
=> Update position of shuffle button

plugin/assets/src/customizer/components/color-control/index.js
=> Allow deselect color in color picker

plugin/assets/css/src/block-editor.css
=> Add missing token equivalences

.stylelintrc.json, package-lock.json, package.json, plugin/assets/css/src/components/floating-label.css, plugin/assets/css/src/components/form-field.css, plugin/assets/css/src/components/material.css, plugin/assets/css/src/components/text-field.css, plugin/assets/css/src/material-components.css, plugin/assets/css/src/overrides.css, theme/assets/css/src/components/material.css, theme/assets/css/src/material-components.css
=> M3 Text field

plugin/assets/src/block-editor/blocks/tab-bar/deprecated.js, plugin/assets/src/block-editor/blocks/tab-bar/deprecated/m2/m2-tab-save.js, plugin/assets/src/block-editor/blocks/tab-bar/index.js
=> Handle tab depreciation

plugin/assets/css/src/components/tooltip.css, plugin/assets/css/src/material-components.css
=> M3 tooltip

plugin/assets/css/src/components/checkbox.css, plugin/assets/css/src/material-components.css, theme/assets/css/src/material-components.css
=> M3 Checkbox

plugin/material-design.php, plugin/php/blocks/class-blocks.php, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt, theme/style.css
=> Fix block.json path
