material-components/material-design-for-wordpress

bin/local-dev/wordpress/Dockerfile, bin/local-dev/wordpress/config/php/xdebug.ini
Fixes #88 
Steps:
1. `npm run env:stop`
1. `docker rmi material-design-for-wordpress_wordpress`
1. `npm run start` # rebuild image.
Follow steps to reproduce from https://github.com/material-components/material-design-for-wordpress/issues/88
=> Allow xdebug connection

plugin/php/block-patterns/call-to-action-features.php, plugin/php/block-patterns/highlights.php, plugin/php/block-patterns/numbers.php, plugin/php/class-block-patterns.php, plugin/tests/phpunit/php/class-test-block-patterns.php
- Uses h3 for title. 
- Uses 40px spacer above each list item to match with h3 padding.
- Uses h5 has item heading. 
- Uses 5% width column for space between highlight title and items.
- Uses h2 for title. 
- Uses h3 for item title. 
- Uses 30px spacer below each column for space in mobile.
- Uses h2 for title. 
- Uses h5 for item title.
- Uses 30px spacer below each column for space in mobile.
<details><summary>Desktop</summary>
<p>
</p>
</details>
<details><summary>Mobile</summary>
<p>
</p>
</details>
Mobile:
Fixes #41
Fixes #42
Fixes #103
=> Highlights, Numbers and Features pattern (with icon)

bin/local-dev/wordpress/Dockerfile
Docker build is using a script to install node and yarn. 
Which fails with the following error: 
```
gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys B9E2F5981AA6E0CD28160D9FF13993A75599653C
gpg: keyserver receive failed: No keyserver available
```
We do not have a dependency on having node, yarn and npm on docker image.
=> Remove node(npm, yarn) from docker build 📦 

plugin/php/class-importer.php
Fixes error of `Uncaught Error: Class 'MaterialDesign\\Plugin\\WP_Error' not found`.
Fixes #
=> Fix WP_Error import

plugin/assets/css/src/customize-controls.css, plugin/assets/src/block-editor/blocks/card/index.js, plugin/assets/src/block-editor/blocks/cards-collection/index.js, plugin/assets/src/block-editor/blocks/contact-form/index.js, plugin/assets/src/block-editor/blocks/hand-picked-posts/index.js, plugin/assets/src/block-editor/blocks/recent-posts/index.js, plugin/assets/src/block-editor/utils/is-default-card-style-outlined.js, plugin/assets/src/block-editor/utils/is-default-text-field-outlined.js, plugin/assets/src/front-end/global-style.js, plugin/assets/src/front-end/index.js, plugin/php/class-block-types.php, plugin/php/class-plugin.php, plugin/php/customizer/class-controls.php, plugin/php/templates/partials/single-post.php, plugin/tests/phpunit/php/class-test-block-types.php, plugin/tests/phpunit/php/customizer/class-test-controls.php, theme/comments.php, theme/functions.php, theme/searchform.php, theme/template-parts/content.php, theme/template-parts/search-archive.php
- Adds setting in plugin for global card and text field.
- Sets default block value based on setting in Gutenberg editor for card and text.
- Uses JS to toggle class to outlined or elevated for card and text field when inherited is not selected.
- Global setting also changes material theme's default text field like search.
See #59 #60
Demo:
https://user-images.githubusercontent.com/5015489/122202434-aefd3200-ceba-11eb-900f-b73d179d946e.mp4
=> Use JS to override global style

plugin/material-design.php, plugin/readme.md, plugin/readme.txt, theme/README.md, theme/readme.txt, theme/style.css
For the full list of changes in this release, please see the [Milestone 0.4.0](https://github.com/material-components/material-design-for-wordpress/issues?q=is%3Aissue+milestone%3A0.4.0).
https://user-images.githubusercontent.com/5015489/132191348-a06e9385-e6d2-431a-b5b4-7f263b741d7d.mp4
-  **Dark mode**:  Pick a dark mode from an existing theme or create your own custom theme and generate a customized dark theme from it.
- Manually turn on/off dark mode or automatically based on the user's system preference. 
- Allow user to switch between light and dark mode via switcher.
- Add inline Icon in paragraphs. (https://github.com/material-components/material-design-for-wordpress/issues/79)
- Add meta tag in header (https://github.com/material-components/material-design-for-wordpress/issues/192 …
=> Bump version to 0.4.0

plugin/assets/src/block-editor/blocks/card/components/inspector-controls-style-panel.js, plugin/assets/src/block-editor/blocks/card/components/vertical-card-layout.js, plugin/assets/src/block-editor/blocks/cards-collection/block.json, plugin/assets/src/block-editor/blocks/cards-collection/components/cards-collection-inspector-controls.js, plugin/assets/src/block-editor/blocks/cards-collection/components/cards.js, plugin/assets/src/block-editor/blocks/cards-collection/constants.js, plugin/assets/src/block-editor/blocks/cards-collection/deprecated.js, plugin/assets/src/block-editor/blocks/cards-collection/edit.js, plugin/assets/src/block-editor/blocks/cards-collection/index.js, plugin/assets/src/block-editor/components/card-styles-panel/index.js, plugin/assets/src/block-editor/components/card-styles-panel/style.css, plugin/tests/e2e/specs/block-editor/blocks/recent-posts/recent-posts.spec.js, plugin/tests/js/block-editor/blocks/card/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/card/__snapshots__/save.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/__snapshots__/inspector-controls-style-panel.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/__snapshots__/vertical-card-layout.test.js.snap, plugin/tests/js/block-editor/blocks/card/components/inspector-controls-style-panel.test.js, plugin/tests/js/block-editor/blocks/cards-collection/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/cards-collection/cards-collection.test.js, plugin/tests/js/block-editor/blocks/cards-collection/components/__snapshots__/cards-collection-inspector-controls.test.js.snap, plugin/tests/js/block-editor/blocks/cards-collection/edit.test.js, plugin/tests/js/block-editor/blocks/hand-picked-posts/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/blocks/hand-picked-posts/hand-picked-posts.test.js, plugin/tests/js/block-editor/blocks/recent-posts/__snapshots__/edit.test.js.snap, plugin/tests/js/block-editor/components/card-styles-panel/__snapshots__/index.test.js.snap, plugin/tests/js/block-editor/components/card-styles-panel/index.test.js
=> Card collection updates

plugin/php/class-plugin.php, plugin/php/customizer/class-controls.php, plugin/php/customizer/class-material-color-palette-control.php, plugin/tests/phpunit/php/customizer/class-test-controls.php, theme/assets/src/customizer/customize-preview.js, theme/inc/customizer.php, theme/inc/customizer/colors.php, theme/theme.json
- Map color with Material colors in customizer.
- Auto refresh material color on change in customizer color.
Fixes #
Demo:
https://user-images.githubusercontent.com/5015489/146341259-fb9ae3b9-7951-4753-aae1-db1b8de0e9bb.mp4
=> Add colors in theme.json

theme/assets/css/src/base/masonry-grid.css, theme/assets/css/src/editor.css, theme/assets/src/block-editor/blocks/card/block.json, theme/assets/src/block-editor/blocks/card/edit.js, theme/assets/src/block-editor/blocks/card/icon.js, theme/assets/src/block-editor/blocks/card/index.js, theme/assets/src/block-editor/blocks/card/inspectControl.js, theme/assets/src/block-editor/blocks/card/save.js, theme/assets/src/block-editor/plugins/style/core-template/index.js, theme/assets/src/front-end/components/masonry.js, theme/block-templates/search.html, theme/functions.php, theme/inc/blocks/class-blocks.php, theme/template-parts/blocks/card-query.php
- Insert material query loop card in post template.
- Tweak Date, author, comments, summary.
- Post template has masonary grid. 
Fixes #237
=> Add card block

Gruntfile.js, theme/assets/src/block-editor/blocks/back-to-top/block.json, theme/assets/src/block-editor/blocks/card/block.json, theme/assets/src/block-editor/blocks/dark-mode-switch/block.json, theme/assets/src/block-editor/blocks/search/block.json, theme/inc/block-editor.php
Allow block.json to be part of build.
Fixes #
=> Whitelist block.json in theme bundle

theme/template-parts/blocks/query-pagination-first.php, theme/template-parts/blocks/query-pagination-last.php, theme/template-parts/blocks/query-pagination-next.php, theme/template-parts/blocks/query-pagination-previous.php
Previously pagination not showing links altogether instead use
disabled state when links are not required for a given page.
Example: On last pagination page, the last page link is disabled instead
of being visible.
Demo:
https://user-images.githubusercontent.com/5015489/152501562-a0a04972-23c2-4ef5-afd8-c8f143dcd3ed.mp4
Fixes #236
=> Pagination use disabled links

theme/inc/blocks/class-blocks.php
Fixes issue when adding query loop with material card shows posts being editing for all cards.
<details><summary>Before</summary>
<p>
</p>
</details>
<details><summary>After</summary>
<p>
</p>
</details>
Fixes #237
=> Fix context for card

theme/assets/src/front-end/components/masonry.js
<details><summary>Screenshot</summary>
<p>
</p>
</details>
Fixes #
=> Add masonry for default post template

theme/assets/src/block-editor/index.js, theme/assets/src/block-editor/plugins/post-navigation-link/edit.js, theme/assets/src/block-editor/plugins/post-navigation-link/index.js, theme/block-templates/single.html, theme/inc/blocks/class-override.php
- Overrides `core/post-navigation-link` block to add custom position.
Fixes #299 
| Before | After |
|--------|-------|
|  <img width="885" alt="image" src="https://user-images.githubusercontent.com/5015489/155100659-ccd1d93f-2fc5-4dc1-a647-eee228496a3c.png"> | <img width="893" alt="image" src="https://user-images.githubusercontent.com/5015489/155100584-134d975a-2df1-40bc-ae86-427610b73eae.png"> |
Demo:
https://user-images.githubusercontent.com/5015489/155152288-b2cf8053-2e5e-4531-85dd-a754ae8cdb02.mp4
=> FSE: Override post navigation next → icon after the post title

plugin/assets/src/block-editor/components/circular-option-picker/style.css
Fix color spacing on FSE.
Fixes #
=> Fix color spacing

theme/assets/css/src/base/typography.css, theme/assets/css/src/components/top-app-bar.css, theme/assets/src/block-editor/hooks.js, theme/inc/block-editor.php, theme/inc/customizer/colors.php, theme/parts/header.html, theme/parts/subtitle.html, theme/parts/title.html, theme/templates/page.html, theme/templates/single.html, theme/theme.json
- Register m2 typography tokens in Gutenberg. 
- Allow user to pick typography tokens. 
- Remove class names added to FSE template for m2 typography.
Dependency on PR #356
Fixes #147
=> Allow user to pick m2 typography tokens; Update fse template

theme/inc/block-editor.php
Call `enqueue_block_editor_assets` filter early to inject in `editor-canvas` iframe.
Fixes #344
=> Enqueue block editor assets early for FSE

theme/template-parts/blocks/navigation-link.php
Fixes #235 
Adds active indicator to drawer menu items
=> Display active indicator inside drawer

plugin/assets/src/block-editor/utils/get-config.js, plugin/assets/src/customizer/components/style-settings-control/index.js, plugin/assets/src/customizer/customize-controls.js, plugin/assets/src/customizer/customize-preview.js, plugin/php/class-plugin.php, plugin/php/customizer/class-controls.php, plugin/php/customizer/class-material-color-palette-control.php, theme/assets/src/front-end/components/dark-mode-switch.js, theme/template-parts/menu-header.php
=> Restore color controls in customizer, and ensure they still work

theme/assets/css/src/material-components.css, theme/assets/css/src/material/top-app-bar.css
=> M3 Top app bar

plugin/assets/css/src/components/tab.css
=> Fix inactive tab color
